<?php

namespace ContainerX7dxWXI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEcoleControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\EcoleController' shared autowired service.
     *
     * @return \App\Controller\EcoleController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\EcoleController'] = $instance = new \App\Controller\EcoleController();

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\EcoleController', $container));

        return $instance;
    }
}
