<?php

namespace ContainerX7dxWXI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getNomRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\NomRepository' shared autowired service.
     *
     * @return \App\Repository\NomRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\NomRepository'] = new \App\Repository\NomRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
