<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMnSF4SH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMnSF4SH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMnSF4SH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMnSF4SH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerMnSF4SH\App_KernelDevDebugContainer([
    'container.build_hash' => 'MnSF4SH',
    'container.build_id' => 'c9c96779',
    'container.build_time' => 1754387569,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMnSF4SH');
