<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX7dxWXI\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX7dxWXI/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX7dxWXI.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX7dxWXI\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerX7dxWXI\App_KernelDevDebugContainer([
    'container.build_hash' => 'X7dxWXI',
    'container.build_id' => '31a3ded4',
    'container.build_time' => 1753612236,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX7dxWXI');
