<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerY8iJLcb\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerY8iJLcb/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerY8iJLcb.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerY8iJLcb\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerY8iJLcb\App_KernelDevDebugContainer([
    'container.build_hash' => 'Y8iJLcb',
    'container.build_id' => '5f0bbda1',
    'container.build_time' => 1754243306,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerY8iJLcb');
