<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'Home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], [], []],
    'app_ecole' => [[], ['_controller' => 'App\\Controller\\EcoleController::index'], [], [['text', '/ecole']], [], [], []],
    'app_home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/home']], [], [], []],
    'app_home_dashboard' => [[], ['_controller' => 'App\\Controller\\HomeController::Dashboard'], [], [['text', '/home/dashboard']], [], [], []],
    'app_mobile' => [[], ['_controller' => 'App\\Controller\\MobileController::index'], [], [['text', '/mobile']], [], [], []],
    'app_mobile_validate' => [[], ['_controller' => 'App\\Controller\\MobileController::validate'], [], [['text', '/mobile/validate']], [], [], []],
    'app_produit' => [[], ['_controller' => 'App\\Controller\\ProduitController::index'], [], [['text', '/produit']], [], [], []],
    'app_produit_create' => [[], ['_controller' => 'App\\Controller\\ProduitController::create'], [], [['text', '/produit/create']], [], [], []],
    'app_produit_list' => [[], ['_controller' => 'App\\Controller\\ProduitController::edit'], [], [['text', '/produit/list']], [], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/login']], [], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\UserController::logout'], [], [['text', '/logout']], [], [], []],
    'app_list' => [[], ['_controller' => 'App\\Controller\\UserController::list'], [], [['text', '/list']], [], [], []],
];
